---
- name: Add apt repository
  apt_repository: repo='ppa:jonathonf/vim' state=present

- name: update apt
  apt: name={{ item }} cache_valid_time=0 state=latest update_cache=yes
  sudo: yes
  with_items:
    - zsh
    - git
    - vim
    - vim-nox
    - vim-nox-py2
    - ctags
    - build-essential
    - cmake
    - python-dev
    - silversearcher-ag
    - tmux
    - automake
    - bison
    - flex
    - g++
    - libboost1.55-all-dev
    - libevent-dev
    - libssl-dev
    - libtool
    - make
    - pkg-config
  register: installation

- name: Backing up existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc .zshrc.origin; fi
  when: installation|success

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: installation|success
  register: cloning
  sudo: no

- name: Creating new ~/.zshrc
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: cloning|success
  sudo: no

- name: Set zsh as default shell
  shell: chsh -s /usr/bin/zsh

- name: Download pip files
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/root/get-pip.py

- name: Install pip
  shell: python /root/get-pip.py

- name: Install pip packages
  pip: name={{ item }}
  sudo: yes
  with_items:
    - pyflakes
    - pylint
    - pep8
    - virtualenv
